# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 066569badd795b29fc67d2a0a94c23892b957d6aad4e37736cca4d6a0cfa3a0950f5270f85bf88568dbe84da51688f1f37184fc552106e85bf1695dd7656a21c

test:
  secret_key_base: 49c52548f0c71c952686f2fe461767c365206c64e00ba34f12406eb31760a4959895c9dbce4b5195dd4952f45221828f2a43afd9b1732f18d642165e6d51647f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
